<?php

/**
 * This is the model base class for the table "wp_bp_friends".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WpBpFriends".
 *
 * Columns in table "wp_bp_friends" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $initiator_user_id
 * @property string $friend_user_id
 * @property integer $is_confirmed
 * @property integer $is_limited
 * @property string $date_created
 *
 */
abstract class BaseWpBpFriends extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'wp_bp_friends';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WpBpFriends|WpBpFriends', $n);
	}

	public static function representingColumn() {
		return 'date_created';
	}

	public function rules() {
		return array(
			array('initiator_user_id, friend_user_id, date_created', 'required'),
			array('is_confirmed, is_limited', 'numerical', 'integerOnly'=>true),
			array('initiator_user_id, friend_user_id', 'length', 'max'=>20),
			array('is_confirmed, is_limited', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, initiator_user_id, friend_user_id, is_confirmed, is_limited, date_created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'initiator_user_id' => Yii::t('app', 'Initiator User'),
			'friend_user_id' => Yii::t('app', 'Friend User'),
			'is_confirmed' => Yii::t('app', 'Is Confirmed'),
			'is_limited' => Yii::t('app', 'Is Limited'),
			'date_created' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('initiator_user_id', $this->initiator_user_id, true);
		$criteria->compare('friend_user_id', $this->friend_user_id, true);
		$criteria->compare('is_confirmed', $this->is_confirmed);
		$criteria->compare('is_limited', $this->is_limited);
		$criteria->compare('date_created', $this->date_created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}