<?php

/**
 * This is the model base class for the table "wp_service".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Service".
 *
 * Columns in table "wp_service" available as properties of the model,
 * followed by relations of table "wp_service" available as properties of the model.
 *
 * @property integer $id
 * @property string $servicename
 * @property integer $sortorder
 *
 * @property Foundboxvideos[] $foundboxvideoses
 */
abstract class BaseService extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'wp_service';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Service|Services', $n);
	}

	public static function representingColumn() {
		return 'servicename';
	}

	public function rules() {
		return array(
			array('sortorder', 'numerical', 'integerOnly'=>true),
			array('servicename', 'length', 'max'=>250),
			array('servicename, sortorder', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, servicename, sortorder', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'foundboxvideoses' => array(self::HAS_MANY, 'Foundboxvideos', 'ff_services_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'servicename' => Yii::t('app', 'Servicename'),
			'sortorder' => Yii::t('app', 'Sortorder'),
			'foundboxvideoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('servicename', $this->servicename, true);
		$criteria->compare('sortorder', $this->sortorder);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}